language: python
python:
  - "2.7"
  - "3.6"

sudo: false

addons:
  apt:
    packages:
    - wget
    - libgmp-dev
    - libffi6
    - ocl-icd-libopencl1
    - opencl-headers

before_install:
 # install Futhark
 - wget http://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
 - tar xf futhark-nightly-linux-x86_64.tar.xz
 - (cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)

install:
  - pip install -r requirements.txt

script:
  - make
